/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package espanholol.studio;

import espanholol.*;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

/**
 *
 * @author DG
 */
public class EspanhololFRM extends javax.swing.JFrame {

    
    private static int cont = 0;
    private static EspanhololFRM fRMMarotageLanguage;
    
    /**
     * Creates new form MarotageFRM
     */
    public EspanhololFRM() {
        initComponents();
        jtaCodigoFonte.setForeground(Color.GREEN);
        jtaCodigoFonte.setBackground(Color.BLACK);
        GridBagLayout layout = new GridBagLayout();
        layout.columnWidths = new int[] {200, 1};
        //layout.
        jpResultado.setLayout(layout);
        setExtendedState(MAXIMIZED_BOTH);
    }
    
     public static synchronized EspanhololFRM getInstance() {

        if (getfRMMarotageLanguage() == null) {
            setfRMMarotageLanguage(new EspanhololFRM());
            System.out.println(cont++);
        }
        return getfRMMarotageLanguage();
    }
     
     /**
     * @return the fRMMarotageLanguage
     */
    public static EspanhololFRM getfRMMarotageLanguage() {
        return fRMMarotageLanguage;
    }
    
    public void adicionarLog(String texto, Color cor){
        int id = jpResultado.getComponentCount();
        JLabel label = new JLabel("[" + id + "] " + texto);
        label.setForeground(cor);
        GridBagConstraints c = new GridBagConstraints();
        c.gridy = id;
        c.anchor = GridBagConstraints.WEST;
        c.fill = GridBagConstraints.VERTICAL;
        
        jpResultado.add(label, c);
        jpResultado.revalidate();
        this.getContentPane().revalidate();

    }

     /**
     * @param afRMMarotageLanguage the fRMMarotageLanguage to set
     */
    public static void setfRMMarotageLanguage(EspanhololFRM afRMMarotageLanguage) {
        fRMMarotageLanguage = afRMMarotageLanguage;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtaCodigoFonte = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jbtCompilarExecutar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jpResultado = new javax.swing.JPanel();
        abrirBTN = new javax.swing.JButton();
        salvarBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ML - Marotage Language");

        jtaCodigoFonte.setColumns(20);
        jtaCodigoFonte.setRows(5);
        jScrollPane1.setViewportView(jtaCodigoFonte);

        jLabel1.setText("Crie seu código fonte");

        jbtCompilarExecutar.setText("Compilar/Executar");
        jbtCompilarExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCompilarExecutarActionPerformed(evt);
            }
        });

        jLabel2.setText("Saída");

        jpResultado.setBackground(new java.awt.Color(0, 0, 0));
        jpResultado.setForeground(new java.awt.Color(255, 255, 255));
        jpResultado.setEnabled(false);
        jpResultado.setPreferredSize(new java.awt.Dimension(0, 150));

        javax.swing.GroupLayout jpResultadoLayout = new javax.swing.GroupLayout(jpResultado);
        jpResultado.setLayout(jpResultadoLayout);
        jpResultadoLayout.setHorizontalGroup(
            jpResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );
        jpResultadoLayout.setVerticalGroup(
            jpResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        abrirBTN.setText("Abrir");
        abrirBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirBTNActionPerformed(evt);
            }
        });

        salvarBTN.setText("Salvar");
        salvarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                        .addComponent(salvarBTN)
                        .addGap(18, 18, 18)
                        .addComponent(abrirBTN)
                        .addGap(18, 18, 18)
                        .addComponent(jbtCompilarExecutar))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jbtCompilarExecutar)
                    .addComponent(abrirBTN)
                    .addComponent(salvarBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jpResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(754, 443));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCompilarExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCompilarExecutarActionPerformed
        try {
            String texto = jtaCodigoFonte.getText();
            Lexico lex = new Lexico(texto);
            Sintatico sin = new Sintatico();
            Semantico sem = new Semantico();
            sin.parse(lex, sem);
            
            adicionarLog("Código analisado com sucesso.", Color.GREEN);
        } catch (LexicalError | SemanticError |SyntaticError ex) {
            Logger.getLogger(EspanhololStudio.class.getName()).log(Level.SEVERE, null, ex);
            adicionarLog("Erro no código. Deve estar faltando um ;", Color.RED);
        } 
    }//GEN-LAST:event_jbtCompilarExecutarActionPerformed

    private void abrirBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirBTNActionPerformed
        final JFileChooser fc = new JFileChooser();
        int option = fc.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fc.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            String content = FileIOManager.getFileContent(path);
            jtaCodigoFonte.setText(content);
        }
    }//GEN-LAST:event_abrirBTNActionPerformed

    private void salvarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBTNActionPerformed
        final JFileChooser fc = new JFileChooser();
        int option = fc.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fc.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            FileIOManager.createFileAndWrite(path, jtaCodigoFonte.getText());
        }
    }//GEN-LAST:event_salvarBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspanhololFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspanhololFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspanhololFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspanhololFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EspanhololFRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtCompilarExecutar;
    private javax.swing.JPanel jpResultado;
    private javax.swing.JTextArea jtaCodigoFonte;
    private javax.swing.JButton salvarBTN;
    // End of variables declaration//GEN-END:variables

   

   
}

